version: '3.8'

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  grafana:
    image: grafana/grafana-oss:8.4.1
    ports:
      - 3000:3000
    user: '104'
    networks:
      - monitoring
    volumes:
      # - ./config/grafana.ini:/etc/grafana/grafana.ini
      - ./config/grafana/dashboards:/var/lib/grafana/dashboards
      # - ./config/grafana/datasources:/etc/grafana/datasources
      # - ./config/grafana/plugins:/var/lib/grafana/plugins
      - grafana_data:/var/lib/grafana

  prometheus:
    image: prom/prometheus:latest
    # container_name: prometheus_1
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    expose:
      - 9090
    ports:
      - "9090:9090"
    networks:
      - monitoring

  blackbox-exporter:
    image: prom/blackbox-exporter:latest
    # container_name: blackbox-exporter
    restart: unless-stopped
    volumes:
      - ./blackbox.yml:/config/blackbox.yml
    command: --config.file=/config/blackbox.yml
    ports:
      - "9115:9115"
    expose:
      - 9115
    networks:
      - monitoring